apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxdeployment
  namespace: testcarlos
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: git-clone
        image: alpine/git:latest
        env:
        - name: GIT_USER
          valueFrom:
            secretKeyRef:
              name: github-creds
              key: username
        - name: GIT_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-creds
              key: token
        command:
          - /bin/sh
          - -c
          - |
            # Clone the repository using the credentials stored in GIT_USER and GIT_TOKEN
            git clone --depth=1 https://${GIT_USER}:${GIT_TOKEN}@github.com/Carlossawan/basic-nginx.git /tmp/repo && \
            cp -r /tmp/repo/* /usr/share/nginx/html/
        volumeMounts:
        - name: static-files
          mountPath: /usr/share/nginx/html
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          name: "nginx-port"
        volumeMounts:
        - name: static-files
          mountPath: /usr/share/nginx/html
      volumes:
      - name: static-files
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: testcarlos
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
